# Тема "Вычисления с помощью Numpy"

Задание 1

In [43]:
import numpy as np

In [21]:
a = np.array([[1, 6],
             [2, 8],
             [3, 11],
             [3, 10],
             [1, 7]])

In [22]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [25]:
mean_a = a.mean(axis=0)

In [26]:
mean_a

array([2. , 8.4])

Задание 2

In [29]:
a_centered = a - mean_a

In [32]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

Задание 3

In [47]:
a_centered_sp = np.dot(a_centered[:, 0], a_centered[:, 1])/(a.shape[0] - 1)

In [48]:
a_centered_sp

2.0

Задание 4

In [50]:
np.cov(a.T)[0, 1]

2.0

# Тема “Работа с данными в Pandas”

Задание 1

In [1]:
import pandas as pd

In [2]:
authors = pd.DataFrame({'author_id':[1, 2, 3],
                        'author_name':['Turgenev', 'Chekhov', 'Ostrovsky']},
                      columns=['author_id', 'author_name'])

In [3]:
authors

author_id author_name
0          1    Turgenev
1          2     Chekhov
2          3   Ostrovsky

In [4]:
book = pd.DataFrame({'author_id':[1, 1, 1, 2, 2, 3, 3],
                    'book_title':['Fathers and Sons', 'Rudin', 'Noble Nest', 'Thick and thin', 'Lady with a dog', 'Thunderstorm', 'Talents and fans'],
                    'price':[450, 300, 350, 500, 450, 370, 290]},
                   columns=['author_id', 'book_title', 'price'])

In [5]:
book

author_id        book_title  price
0          1  Fathers and Sons    450
1          1             Rudin    300
2          1        Noble Nest    350
3          2    Thick and thin    500
4          2   Lady with a dog    450
5          3      Thunderstorm    370
6          3  Talents and fans    290

Задание 2

In [6]:
authors_price = pd.merge(authors, book, on='author_id', how='right')

In [7]:
authors_price

author_id author_name        book_title  price
0          1    Turgenev  Fathers and Sons    450
1          1    Turgenev             Rudin    300
2          1    Turgenev        Noble Nest    350
3          2     Chekhov    Thick and thin    500
4          2     Chekhov   Lady with a dog    450
5          3   Ostrovsky      Thunderstorm    370
6          3   Ostrovsky  Talents and fans    290

Задание 3

In [19]:
top5 = authors_price.nlargest(5, 'price')
top5

author_id author_name        book_title  price
3          2     Chekhov    Thick and thin    500
0          1    Turgenev  Fathers and Sons    450
4          2     Chekhov   Lady with a dog    450
5          3   Ostrovsky      Thunderstorm    370
2          1    Turgenev        Noble Nest    350

Задание 4

In [38]:
authors_min = authors_price.groupby('author_name').agg({'price':'min'})
authors_min = authors_min.rename(columns={'price':'min_price'})
authors_min

min_price
author_name           
Chekhov            450
Ostrovsky          290
Turgenev           300

In [34]:
authors_max = authors_price.groupby('author_name').agg({'price':'max'})
authors_max = authors_max.rename(columns={'price':'max_price'})
authors_max

max_price
author_name           
Chekhov            500
Ostrovsky          370
Turgenev           450

In [35]:
authors_mean = authors_price.groupby('author_name').agg({'price':'mean'})
authors_mean = authors_mean.rename(columns={'price':'mean_price'})
authors_mean

mean_price
author_name            
Chekhov      475.000000
Ostrovsky    330.000000
Turgenev     366.666667

In [36]:
authors_min_max = pd.merge(authors_min, authors_max, on='author_name', how='inner')
authors_min_max

min_price  max_price
author_name                      
Chekhov            450        500
Ostrovsky          290        370
Turgenev           300        450

In [37]:
authors_stat = pd.merge(authors_min_max, authors_mean, on='author_name', how='inner')
authors_stat

min_price  max_price  mean_price
author_name                                  
Chekhov            450        500  475.000000
Ostrovsky          290        370  330.000000
Turgenev           300        450  366.666667

Задание 5**

In [39]:
covers = ['hard', 'soft', 'soft', 'hard', 'hard', 'soft', 'soft']

In [40]:
authors_price['cover'] = covers
authors_price

author_id author_name        book_title  price cover
0          1    Turgenev  Fathers and Sons    450  hard
1          1    Turgenev             Rudin    300  soft
2          1    Turgenev        Noble Nest    350  soft
3          2     Chekhov    Thick and thin    500  hard
4          2     Chekhov   Lady with a dog    450  hard
5          3   Ostrovsky      Thunderstorm    370  soft
6          3   Ostrovsky  Talents and fans    290  soft

In [41]:
? pd.pivot_table

In [46]:
book_info = pd.pivot_table(authors_price, values='price', index='author_name', columns='cover', aggfunc=np.sum)
book_info['hard'].fillna(0, inplace=True)
book_info['soft'].fillna(0, inplace=True)
book_info

cover         hard   soft
author_name              
Chekhov      950.0    0.0
Ostrovsky      0.0  660.0
Turgenev     450.0  650.0

In [47]:
book_info.to_pickle('book_info.pkl')

In [48]:
book_info2 = pd.read_pickle('book_info.pkl')
book_info2

cover         hard   soft
author_name              
Chekhov      950.0    0.0
Ostrovsky      0.0  660.0
Turgenev     450.0  650.0